#ifndef SDKCONFIG_H
#define SDKCONFIG_H

//#define CONFIG_SPIRAM_SUPPORT 1
//#define CONFIG_ESP32S3_SPIRAM_SUPPORT 1
//#define CONFIG_SPIRAM_CACHE_WORKAROUND 1
//#define CONFIG_ESP32S3_DEFAULT_PSRAM_CS_IO 26
//#define CONFIG_SPIRAM_MODE_OCT 1

#endif // SDKCONFIG_H